/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZoomParallaxDemoRouteImport } from './routes/zoom-parallax-demo'
import { Route as RoleRouteImport } from './routes/role'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerIndexRouteImport } from './routes/seller.index'
import { Route as BuyerIndexRouteImport } from './routes/buyer.index'
import { Route as SellerRegisterRouteImport } from './routes/seller.register'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerListingsRouteImport } from './routes/seller.listings'
import { Route as SellerAnalyticsRouteImport } from './routes/seller.analytics'
import { Route as SellerAccountRouteImport } from './routes/seller.account'
import { Route as BuyerRegisterRouteImport } from './routes/buyer.register'
import { Route as BuyerProfileRouteImport } from './routes/buyer.profile'
import { Route as BuyerOrdersRouteImport } from './routes/buyer.orders'
import { Route as BuyerNotificationsRouteImport } from './routes/buyer.notifications'
import { Route as BuyerBrowseRouteImport } from './routes/buyer.browse'
import { Route as AdminLayoutRouteImport } from './routes/admin.layout'
import { Route as SellerListingsNewRouteImport } from './routes/seller.listings.new'
import { Route as BuyerProductIdRouteImport } from './routes/buyer.product.$id'
import { Route as BuyerCheckoutIdRouteImport } from './routes/buyer.checkout.$id'
import { Route as AdminLayoutSettingsRouteImport } from './routes/admin.layout.settings'
import { Route as AdminLayoutSellersRouteImport } from './routes/admin.layout.sellers'
import { Route as AdminLayoutPayoutsRouteImport } from './routes/admin.layout.payouts'
import { Route as AdminLayoutListingsRouteImport } from './routes/admin.layout.listings'
import { Route as AdminLayoutKycRouteImport } from './routes/admin.layout.kyc'
import { Route as AdminLayoutHelpRouteImport } from './routes/admin.layout.help'
import { Route as AdminLayoutDisputesRouteImport } from './routes/admin.layout.disputes'
import { Route as AdminLayoutDashboardRouteImport } from './routes/admin.layout.dashboard'
import { Route as AdminLayoutAuditLogsRouteImport } from './routes/admin.layout.audit-logs'
import { Route as AdminLayoutAnalyticsRouteImport } from './routes/admin.layout.analytics'

const ZoomParallaxDemoRoute = ZoomParallaxDemoRouteImport.update({
  id: '/zoom-parallax-demo',
  path: '/zoom-parallax-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/seller/',
  path: '/seller/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerIndexRoute = BuyerIndexRouteImport.update({
  id: '/buyer/',
  path: '/buyer/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRegisterRoute = SellerRegisterRouteImport.update({
  id: '/seller/register',
  path: '/seller/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/seller/orders',
  path: '/seller/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerListingsRoute = SellerListingsRouteImport.update({
  id: '/seller/listings',
  path: '/seller/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerAnalyticsRoute = SellerAnalyticsRouteImport.update({
  id: '/seller/analytics',
  path: '/seller/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerAccountRoute = SellerAccountRouteImport.update({
  id: '/seller/account',
  path: '/seller/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerRegisterRoute = BuyerRegisterRouteImport.update({
  id: '/buyer/register',
  path: '/buyer/register',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerProfileRoute = BuyerProfileRouteImport.update({
  id: '/buyer/profile',
  path: '/buyer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerOrdersRoute = BuyerOrdersRouteImport.update({
  id: '/buyer/orders',
  path: '/buyer/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerNotificationsRoute = BuyerNotificationsRouteImport.update({
  id: '/buyer/notifications',
  path: '/buyer/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerBrowseRoute = BuyerBrowseRouteImport.update({
  id: '/buyer/browse',
  path: '/buyer/browse',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/buyer.browse.lazy').then((d) => d.Route))
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => AdminRoute,
} as any)
const SellerListingsNewRoute = SellerListingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SellerListingsRoute,
} as any).lazy(() =>
  import('./routes/seller.listings.new.lazy').then((d) => d.Route),
)
const BuyerProductIdRoute = BuyerProductIdRouteImport.update({
  id: '/buyer/product/$id',
  path: '/buyer/product/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/buyer.product.$id.lazy').then((d) => d.Route),
)
const BuyerCheckoutIdRoute = BuyerCheckoutIdRouteImport.update({
  id: '/buyer/checkout/$id',
  path: '/buyer/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/buyer.checkout.$id.lazy').then((d) => d.Route),
)
const AdminLayoutSettingsRoute = AdminLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminLayoutRoute,
} as any).lazy(() =>
  import('./routes/admin.layout.settings.lazy').then((d) => d.Route),
)
const AdminLayoutSellersRoute = AdminLayoutSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminLayoutRoute,
} as any).lazy(() =>
  import('./routes/admin.layout.sellers.lazy').then((d) => d.Route),
)
const AdminLayoutPayoutsRoute = AdminLayoutPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminLayoutRoute,
} as any).lazy(() =>
  import('./routes/admin.layout.payouts.lazy').then((d) => d.Route),
)
const AdminLayoutListingsRoute = AdminLayoutListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminLayoutRoute,
} as any).lazy(() =>
  import('./routes/admin.layout.listings.lazy').then((d) => d.Route),
)
const AdminLayoutKycRoute = AdminLayoutKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminLayoutRoute,
} as any).lazy(() =>
  import('./routes/admin.layout.kyc.lazy').then((d) => d.Route),
)
const AdminLayoutHelpRoute = AdminLayoutHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AdminLayoutRoute,
} as any).lazy(() =>
  import('./routes/admin.layout.help.lazy').then((d) => d.Route),
)
const AdminLayoutDisputesRoute = AdminLayoutDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminLayoutRoute,
} as any).lazy(() =>
  import('./routes/admin.layout.disputes.lazy').then((d) => d.Route),
)
const AdminLayoutDashboardRoute = AdminLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminLayoutRoute,
} as any).lazy(() =>
  import('./routes/admin.layout.dashboard.lazy').then((d) => d.Route),
)
const AdminLayoutAuditLogsRoute = AdminLayoutAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminLayoutRoute,
} as any).lazy(() =>
  import('./routes/admin.layout.audit-logs.lazy').then((d) => d.Route),
)
const AdminLayoutAnalyticsRoute = AdminLayoutAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminLayoutRoute,
} as any).lazy(() =>
  import('./routes/admin.layout.analytics.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/role': typeof RoleRoute
  '/zoom-parallax-demo': typeof ZoomParallaxDemoRoute
  '/admin/layout': typeof AdminLayoutRouteWithChildren
  '/buyer/browse': typeof BuyerBrowseRoute
  '/buyer/notifications': typeof BuyerNotificationsRoute
  '/buyer/orders': typeof BuyerOrdersRoute
  '/buyer/profile': typeof BuyerProfileRoute
  '/buyer/register': typeof BuyerRegisterRoute
  '/seller/account': typeof SellerAccountRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/listings': typeof SellerListingsRouteWithChildren
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/register': typeof SellerRegisterRoute
  '/buyer/': typeof BuyerIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/admin/layout/analytics': typeof AdminLayoutAnalyticsRoute
  '/admin/layout/audit-logs': typeof AdminLayoutAuditLogsRoute
  '/admin/layout/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/layout/disputes': typeof AdminLayoutDisputesRoute
  '/admin/layout/help': typeof AdminLayoutHelpRoute
  '/admin/layout/kyc': typeof AdminLayoutKycRoute
  '/admin/layout/listings': typeof AdminLayoutListingsRoute
  '/admin/layout/payouts': typeof AdminLayoutPayoutsRoute
  '/admin/layout/sellers': typeof AdminLayoutSellersRoute
  '/admin/layout/settings': typeof AdminLayoutSettingsRoute
  '/buyer/checkout/$id': typeof BuyerCheckoutIdRoute
  '/buyer/product/$id': typeof BuyerProductIdRoute
  '/seller/listings/new': typeof SellerListingsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/role': typeof RoleRoute
  '/zoom-parallax-demo': typeof ZoomParallaxDemoRoute
  '/admin/layout': typeof AdminLayoutRouteWithChildren
  '/buyer/browse': typeof BuyerBrowseRoute
  '/buyer/notifications': typeof BuyerNotificationsRoute
  '/buyer/orders': typeof BuyerOrdersRoute
  '/buyer/profile': typeof BuyerProfileRoute
  '/buyer/register': typeof BuyerRegisterRoute
  '/seller/account': typeof SellerAccountRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/listings': typeof SellerListingsRouteWithChildren
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/register': typeof SellerRegisterRoute
  '/buyer': typeof BuyerIndexRoute
  '/seller': typeof SellerIndexRoute
  '/admin/layout/analytics': typeof AdminLayoutAnalyticsRoute
  '/admin/layout/audit-logs': typeof AdminLayoutAuditLogsRoute
  '/admin/layout/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/layout/disputes': typeof AdminLayoutDisputesRoute
  '/admin/layout/help': typeof AdminLayoutHelpRoute
  '/admin/layout/kyc': typeof AdminLayoutKycRoute
  '/admin/layout/listings': typeof AdminLayoutListingsRoute
  '/admin/layout/payouts': typeof AdminLayoutPayoutsRoute
  '/admin/layout/sellers': typeof AdminLayoutSellersRoute
  '/admin/layout/settings': typeof AdminLayoutSettingsRoute
  '/buyer/checkout/$id': typeof BuyerCheckoutIdRoute
  '/buyer/product/$id': typeof BuyerProductIdRoute
  '/seller/listings/new': typeof SellerListingsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/role': typeof RoleRoute
  '/zoom-parallax-demo': typeof ZoomParallaxDemoRoute
  '/admin/layout': typeof AdminLayoutRouteWithChildren
  '/buyer/browse': typeof BuyerBrowseRoute
  '/buyer/notifications': typeof BuyerNotificationsRoute
  '/buyer/orders': typeof BuyerOrdersRoute
  '/buyer/profile': typeof BuyerProfileRoute
  '/buyer/register': typeof BuyerRegisterRoute
  '/seller/account': typeof SellerAccountRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/listings': typeof SellerListingsRouteWithChildren
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/register': typeof SellerRegisterRoute
  '/buyer/': typeof BuyerIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/admin/layout/analytics': typeof AdminLayoutAnalyticsRoute
  '/admin/layout/audit-logs': typeof AdminLayoutAuditLogsRoute
  '/admin/layout/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/layout/disputes': typeof AdminLayoutDisputesRoute
  '/admin/layout/help': typeof AdminLayoutHelpRoute
  '/admin/layout/kyc': typeof AdminLayoutKycRoute
  '/admin/layout/listings': typeof AdminLayoutListingsRoute
  '/admin/layout/payouts': typeof AdminLayoutPayoutsRoute
  '/admin/layout/sellers': typeof AdminLayoutSellersRoute
  '/admin/layout/settings': typeof AdminLayoutSettingsRoute
  '/buyer/checkout/$id': typeof BuyerCheckoutIdRoute
  '/buyer/product/$id': typeof BuyerProductIdRoute
  '/seller/listings/new': typeof SellerListingsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/help'
    | '/login'
    | '/role'
    | '/zoom-parallax-demo'
    | '/admin/layout'
    | '/buyer/browse'
    | '/buyer/notifications'
    | '/buyer/orders'
    | '/buyer/profile'
    | '/buyer/register'
    | '/seller/account'
    | '/seller/analytics'
    | '/seller/listings'
    | '/seller/orders'
    | '/seller/register'
    | '/buyer/'
    | '/seller/'
    | '/admin/layout/analytics'
    | '/admin/layout/audit-logs'
    | '/admin/layout/dashboard'
    | '/admin/layout/disputes'
    | '/admin/layout/help'
    | '/admin/layout/kyc'
    | '/admin/layout/listings'
    | '/admin/layout/payouts'
    | '/admin/layout/sellers'
    | '/admin/layout/settings'
    | '/buyer/checkout/$id'
    | '/buyer/product/$id'
    | '/seller/listings/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/help'
    | '/login'
    | '/role'
    | '/zoom-parallax-demo'
    | '/admin/layout'
    | '/buyer/browse'
    | '/buyer/notifications'
    | '/buyer/orders'
    | '/buyer/profile'
    | '/buyer/register'
    | '/seller/account'
    | '/seller/analytics'
    | '/seller/listings'
    | '/seller/orders'
    | '/seller/register'
    | '/buyer'
    | '/seller'
    | '/admin/layout/analytics'
    | '/admin/layout/audit-logs'
    | '/admin/layout/dashboard'
    | '/admin/layout/disputes'
    | '/admin/layout/help'
    | '/admin/layout/kyc'
    | '/admin/layout/listings'
    | '/admin/layout/payouts'
    | '/admin/layout/sellers'
    | '/admin/layout/settings'
    | '/buyer/checkout/$id'
    | '/buyer/product/$id'
    | '/seller/listings/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/help'
    | '/login'
    | '/role'
    | '/zoom-parallax-demo'
    | '/admin/layout'
    | '/buyer/browse'
    | '/buyer/notifications'
    | '/buyer/orders'
    | '/buyer/profile'
    | '/buyer/register'
    | '/seller/account'
    | '/seller/analytics'
    | '/seller/listings'
    | '/seller/orders'
    | '/seller/register'
    | '/buyer/'
    | '/seller/'
    | '/admin/layout/analytics'
    | '/admin/layout/audit-logs'
    | '/admin/layout/dashboard'
    | '/admin/layout/disputes'
    | '/admin/layout/help'
    | '/admin/layout/kyc'
    | '/admin/layout/listings'
    | '/admin/layout/payouts'
    | '/admin/layout/sellers'
    | '/admin/layout/settings'
    | '/buyer/checkout/$id'
    | '/buyer/product/$id'
    | '/seller/listings/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  RoleRoute: typeof RoleRoute
  ZoomParallaxDemoRoute: typeof ZoomParallaxDemoRoute
  BuyerBrowseRoute: typeof BuyerBrowseRoute
  BuyerNotificationsRoute: typeof BuyerNotificationsRoute
  BuyerOrdersRoute: typeof BuyerOrdersRoute
  BuyerProfileRoute: typeof BuyerProfileRoute
  BuyerRegisterRoute: typeof BuyerRegisterRoute
  SellerAccountRoute: typeof SellerAccountRoute
  SellerAnalyticsRoute: typeof SellerAnalyticsRoute
  SellerListingsRoute: typeof SellerListingsRouteWithChildren
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerRegisterRoute: typeof SellerRegisterRoute
  BuyerIndexRoute: typeof BuyerIndexRoute
  SellerIndexRoute: typeof SellerIndexRoute
  BuyerCheckoutIdRoute: typeof BuyerCheckoutIdRoute
  BuyerProductIdRoute: typeof BuyerProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zoom-parallax-demo': {
      id: '/zoom-parallax-demo'
      path: '/zoom-parallax-demo'
      fullPath: '/zoom-parallax-demo'
      preLoaderRoute: typeof ZoomParallaxDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/seller'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/': {
      id: '/buyer/'
      path: '/buyer'
      fullPath: '/buyer/'
      preLoaderRoute: typeof BuyerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/register': {
      id: '/seller/register'
      path: '/seller/register'
      fullPath: '/seller/register'
      preLoaderRoute: typeof SellerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/seller/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/listings': {
      id: '/seller/listings'
      path: '/seller/listings'
      fullPath: '/seller/listings'
      preLoaderRoute: typeof SellerListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/analytics': {
      id: '/seller/analytics'
      path: '/seller/analytics'
      fullPath: '/seller/analytics'
      preLoaderRoute: typeof SellerAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/account': {
      id: '/seller/account'
      path: '/seller/account'
      fullPath: '/seller/account'
      preLoaderRoute: typeof SellerAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/register': {
      id: '/buyer/register'
      path: '/buyer/register'
      fullPath: '/buyer/register'
      preLoaderRoute: typeof BuyerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/profile': {
      id: '/buyer/profile'
      path: '/buyer/profile'
      fullPath: '/buyer/profile'
      preLoaderRoute: typeof BuyerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/orders': {
      id: '/buyer/orders'
      path: '/buyer/orders'
      fullPath: '/buyer/orders'
      preLoaderRoute: typeof BuyerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/notifications': {
      id: '/buyer/notifications'
      path: '/buyer/notifications'
      fullPath: '/buyer/notifications'
      preLoaderRoute: typeof BuyerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/browse': {
      id: '/buyer/browse'
      path: '/buyer/browse'
      fullPath: '/buyer/browse'
      preLoaderRoute: typeof BuyerBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/layout': {
      id: '/admin/layout'
      path: '/layout'
      fullPath: '/admin/layout'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/seller/listings/new': {
      id: '/seller/listings/new'
      path: '/new'
      fullPath: '/seller/listings/new'
      preLoaderRoute: typeof SellerListingsNewRouteImport
      parentRoute: typeof SellerListingsRoute
    }
    '/buyer/product/$id': {
      id: '/buyer/product/$id'
      path: '/buyer/product/$id'
      fullPath: '/buyer/product/$id'
      preLoaderRoute: typeof BuyerProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/checkout/$id': {
      id: '/buyer/checkout/$id'
      path: '/buyer/checkout/$id'
      fullPath: '/buyer/checkout/$id'
      preLoaderRoute: typeof BuyerCheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/layout/settings': {
      id: '/admin/layout/settings'
      path: '/settings'
      fullPath: '/admin/layout/settings'
      preLoaderRoute: typeof AdminLayoutSettingsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/layout/sellers': {
      id: '/admin/layout/sellers'
      path: '/sellers'
      fullPath: '/admin/layout/sellers'
      preLoaderRoute: typeof AdminLayoutSellersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/layout/payouts': {
      id: '/admin/layout/payouts'
      path: '/payouts'
      fullPath: '/admin/layout/payouts'
      preLoaderRoute: typeof AdminLayoutPayoutsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/layout/listings': {
      id: '/admin/layout/listings'
      path: '/listings'
      fullPath: '/admin/layout/listings'
      preLoaderRoute: typeof AdminLayoutListingsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/layout/kyc': {
      id: '/admin/layout/kyc'
      path: '/kyc'
      fullPath: '/admin/layout/kyc'
      preLoaderRoute: typeof AdminLayoutKycRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/layout/help': {
      id: '/admin/layout/help'
      path: '/help'
      fullPath: '/admin/layout/help'
      preLoaderRoute: typeof AdminLayoutHelpRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/layout/disputes': {
      id: '/admin/layout/disputes'
      path: '/disputes'
      fullPath: '/admin/layout/disputes'
      preLoaderRoute: typeof AdminLayoutDisputesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/layout/dashboard': {
      id: '/admin/layout/dashboard'
      path: '/dashboard'
      fullPath: '/admin/layout/dashboard'
      preLoaderRoute: typeof AdminLayoutDashboardRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/layout/audit-logs': {
      id: '/admin/layout/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/layout/audit-logs'
      preLoaderRoute: typeof AdminLayoutAuditLogsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/layout/analytics': {
      id: '/admin/layout/analytics'
      path: '/analytics'
      fullPath: '/admin/layout/analytics'
      preLoaderRoute: typeof AdminLayoutAnalyticsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutAnalyticsRoute: typeof AdminLayoutAnalyticsRoute
  AdminLayoutAuditLogsRoute: typeof AdminLayoutAuditLogsRoute
  AdminLayoutDashboardRoute: typeof AdminLayoutDashboardRoute
  AdminLayoutDisputesRoute: typeof AdminLayoutDisputesRoute
  AdminLayoutHelpRoute: typeof AdminLayoutHelpRoute
  AdminLayoutKycRoute: typeof AdminLayoutKycRoute
  AdminLayoutListingsRoute: typeof AdminLayoutListingsRoute
  AdminLayoutPayoutsRoute: typeof AdminLayoutPayoutsRoute
  AdminLayoutSellersRoute: typeof AdminLayoutSellersRoute
  AdminLayoutSettingsRoute: typeof AdminLayoutSettingsRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutAnalyticsRoute: AdminLayoutAnalyticsRoute,
  AdminLayoutAuditLogsRoute: AdminLayoutAuditLogsRoute,
  AdminLayoutDashboardRoute: AdminLayoutDashboardRoute,
  AdminLayoutDisputesRoute: AdminLayoutDisputesRoute,
  AdminLayoutHelpRoute: AdminLayoutHelpRoute,
  AdminLayoutKycRoute: AdminLayoutKycRoute,
  AdminLayoutListingsRoute: AdminLayoutListingsRoute,
  AdminLayoutPayoutsRoute: AdminLayoutPayoutsRoute,
  AdminLayoutSellersRoute: AdminLayoutSellersRoute,
  AdminLayoutSettingsRoute: AdminLayoutSettingsRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface AdminRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SellerListingsRouteChildren {
  SellerListingsNewRoute: typeof SellerListingsNewRoute
}

const SellerListingsRouteChildren: SellerListingsRouteChildren = {
  SellerListingsNewRoute: SellerListingsNewRoute,
}

const SellerListingsRouteWithChildren = SellerListingsRoute._addFileChildren(
  SellerListingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  RoleRoute: RoleRoute,
  ZoomParallaxDemoRoute: ZoomParallaxDemoRoute,
  BuyerBrowseRoute: BuyerBrowseRoute,
  BuyerNotificationsRoute: BuyerNotificationsRoute,
  BuyerOrdersRoute: BuyerOrdersRoute,
  BuyerProfileRoute: BuyerProfileRoute,
  BuyerRegisterRoute: BuyerRegisterRoute,
  SellerAccountRoute: SellerAccountRoute,
  SellerAnalyticsRoute: SellerAnalyticsRoute,
  SellerListingsRoute: SellerListingsRouteWithChildren,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerRegisterRoute: SellerRegisterRoute,
  BuyerIndexRoute: BuyerIndexRoute,
  SellerIndexRoute: SellerIndexRoute,
  BuyerCheckoutIdRoute: BuyerCheckoutIdRoute,
  BuyerProductIdRoute: BuyerProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
